const path = require('path');
const fs = require('fs');

const OUTPUT_DIR = path.resolve(__dirname, '../images/china_cities');
const TMP_DIR = '/tmp/china_cities_gen';

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}
if (!fs.existsSync(TMP_DIR)) {
  fs.mkdirSync(TMP_DIR, { recursive: true });
}

const ITEMS = [
  {
    id: 1,
    file: "01_北京.png",
    name: "北京",
    city: "北京",
    region: "华北",
    title: "北京 · 中轴古都天坛祈年",
    features: "天坛祈年殿三重圆形攒尖顶、故宫九梁十八柱角楼、古柏掩映、中轴气象",
    keywords: ["古都", "天坛", "角楼", "中轴", "紫禁城"],
    colors: "故宫朱红 · 琉璃金黄 · 松烟墨黑",
    theme: "Beijing, Temple of Heaven and Imperial Palace Watchtower",
    silhouette: "the majestic circular triple-gabled roof of the Temple of Heaven (Hall of Prayer for Good Harvests) standing prominently, flanked by the ornate multi-eaved corner tower of the Forbidden City and ancient gnarled cypress branches",
    colorPrompt: "imperial cinnabar red, forbidden city ochre gold, and charcoal black"
  },
  {
    id: 2,
    file: "02_上海.png",
    name: "上海",
    city: "上海",
    region: "华东",
    title: "上海 · 浦江东方明珠天际",
    features: "东方明珠广播电视塔、陆家嘴摩天楼群与外滩海关大楼钟楼江湾天际线",
    keywords: ["外滩", "东方明珠", "陆家嘴", "江湾", "摩登"],
    colors: "浅水苍青 · 琉璃金黄 · 浓墨",
    theme: "Shanghai, Oriental Pearl Tower and Bund Skyline across Huangpu River",
    silhouette: "the iconic Oriental Pearl Radio & TV Tower with its spherical tiers rising beside the Shanghai Tower skyline across the curving Huangpu River ripples, facing the historic Bund Customs House clock tower silhouette",
    colorPrompt: "river indigo slate blue, warm sunrise amber gold, and ink black"
  },
  {
    id: 3,
    file: "03_广州.png",
    name: "广州",
    city: "广州",
    region: "华南",
    title: "广州 · 羊城风骨广州塔影",
    features: "广州塔小蛮腰修长扭转钢构、越秀山五羊石雕、珠江游船波光、岭南榕树",
    keywords: ["羊城", "广州塔", "五羊石雕", "珠江", "岭南"],
    colors: "晚霞赤橙 · 珠江蓝 · 炭墨",
    theme: "Guangzhou, Canton Tower and Five Rams Sculpture",
    silhouette: "the slender hyperbolic twisting silhouette of Canton Tower rising beside the classic Five Rams stone sculpture silhouette on Yuexiu Hill, with gentle ripples of the Pearl River and blooming kapok red silk cotton flowers",
    colorPrompt: "sunset terracotta orange, Pearl River deep blue, and charcoal black"
  },
  {
    id: 4,
    file: "04_深圳.png",
    name: "深圳",
    city: "深圳",
    region: "华南",
    title: "深圳 · 鹏城春潮拓荒牛影",
    features: "平安金融中心摩天塔楼、深南大道拓荒牛雕塑、大梅沙海湾帆影",
    keywords: ["鹏城", "平安大厦", "拓荒牛", "春潮", "海湾"],
    colors: "科技深蓝 · 暖金 · 苍石灰",
    theme: "Shenzhen, Ping An Finance Centre and Pioneer Bull Sculpture",
    silhouette: "the towering tapered spire of the Ping An Finance Centre skyline framed by the dynamic energetic silhouette of the Pioneer Bull sculpture charging forward, with coastal mountain contours behind",
    colorPrompt: "deep ocean slate blue, radiant sunrise gold, and granite stone grey"
  },
  {
    id: 5,
    file: "05_成都.png",
    name: "成都",
    city: "成都",
    region: "西南",
    title: "成都 · 锦官天府望江修竹",
    features: "望江楼四层崇丽阁、锦江春水、翠竹丛林、憨态可掬的大熊猫吃竹",
    keywords: ["天府", "望江楼", "锦江", "大熊猫", "翠竹"],
    colors: "翠竹青绿 · 赭石黄 · 松烟黑",
    theme: "Chengdu, Wangjiang Pavilion and Giant Panda in Bamboo Grove",
    silhouette: "the elegant historic Wangjiang Pavilion (Chongli Tower) with flying wooden eaves overlooking the serene Jinjiang River, framed by graceful bamboo stalks and an adorable giant panda peacefully eating a bamboo branch",
    colorPrompt: "mountain bamboo green, antique ochre yellow, and pine soot black"
  },
  {
    id: 6,
    file: "06_重庆.png",
    name: "重庆",
    city: "重庆",
    region: "西南",
    title: "重庆 · 山城吊脚索道跨江",
    features: "洪崖洞叠翠挑梁木质吊脚楼、长江过江索道车厢、轻轨跨桥穿楼山城阶梯",
    keywords: ["山城", "洪崖洞", "长江索道", "吊脚楼", "两江"],
    colors: "吊脚楼赤褐 · 嘉陵水绿 · 暖灯金",
    theme: "Chongqing, Hongyadong Stilt Houses and Yangtze River Cableway",
    silhouette: "the multi-tiered traditional Bayu stilt houses of Hongyadong clinging to a steep cliffside, an overhead Yangtze River cableway car gliding gracefully across the rushing river valley amidst mountain silhouettes",
    colorPrompt: "terracotta brick red, misty river jade green, and warm lantern gold"
  },
  {
    id: 7,
    file: "07_杭州.png",
    name: "杭州",
    city: "杭州",
    region: "华东",
    title: "杭州 · 钱塘湖山断桥夕照",
    features: "西湖断桥残雪石拱、保俶塔雷峰塔遥相对峙、三潭印月石塔、垂柳荷塘",
    keywords: ["西湖", "雷峰塔", "三潭印月", "断桥", "钱塘"],
    colors: "龙井翠绿 · 湖光浅蓝 · 晚霞金",
    theme: "Hangzhou, West Lake Leifeng Pagoda and Three Ponds Mirroring the Moon",
    silhouette: "the storied Leifeng Pagoda silhouette standing upon Sunset Hill across the tranquil West Lake, with stone incense gourds of the Three Ponds Mirroring the Moon in the foreground framed by weeping willow fronds",
    colorPrompt: "Longjing tea green, misty water blue, and warm sunset gold"
  },
  {
    id: 8,
    file: "08_南京.png",
    name: "南京",
    city: "南京",
    region: "华东",
    title: "南京 · 六朝钟阜明城秦淮",
    features: "明城墙中华门三道瓮城、玄武湖远眺紫金山、秦淮河夫子庙大成殿飞檐",
    keywords: ["金陵", "中华门", "明城墙", "秦淮河", "紫金山"],
    colors: "砖石古灰 · 城门暗红 · 苍松绿",
    theme: "Nanjing, Ming City Wall Zhonghua Gate and Qinhuai River",
    silhouette: "the colossal ancient brick fortress arches of Zhonghua Gate along the Ming City Wall, framed by Purple Mountain ridge in the distance and a traditional boat drifting gently on the Qinhuai River with weeping willows",
    colorPrompt: "ancient fortress grey, imperial gate red, and deep pine green"
  },
  {
    id: 9,
    file: "09_武汉.png",
    name: "武汉",
    city: "武汉",
    region: "华中",
    title: "武汉 · 江城黄鹤极目大桥",
    features: "黄鹤楼五层攒尖琉璃飞檐、武汉长江大桥双层桁架如长虹卧波、龟蛇二山",
    keywords: ["江城", "黄鹤楼", "长江大桥", "蛇山", "楚天"],
    colors: "琉璃飞檐黄 · 楚地朱红 · 浩淼江蓝",
    theme: "Wuhan, Yellow Crane Tower and Wuhan Yangtze River Bridge",
    silhouette: "the grand five-tiered Yellow Crane Tower with sweeping curved upturned eaves standing atop Snake Hill, overlooking the monumental steel truss arches of the Wuhan Yangtze River Bridge spanning the mighty river",
    colorPrompt: "glazed tile ochre yellow, Chu cinnabar red, and Yangtze river indigo blue"
  },
  {
    id: 10,
    file: "10_西安.png",
    name: "西安",
    city: "西安",
    region: "西北",
    title: "西安 · 古都长安雁塔钟楼",
    features: "大慈恩寺大雁塔七层方锥砖塔、西安明城墙角楼垛口、西安钟楼重檐",
    keywords: ["长安", "大雁塔", "钟楼", "明城墙", "古都"],
    colors: "关中黄土赭 · 古砖青灰 · 宫墙赤",
    theme: "Xi'an, Giant Wild Goose Pagoda and Ancient City Bell Tower",
    silhouette: "the iconic square pyramidal multi-tiered Giant Wild Goose Pagoda soaring tall, paired with the battlements and watchtower of the ancient Xi'an city wall and the double-roofed Bell Tower silhouette",
    colorPrompt: "terracotta earth ochre, weathered brick grey, and imperial crimson red"
  },
  {
    id: 11,
    file: "11_苏州.png",
    name: "苏州",
    city: "苏州",
    region: "华东",
    title: "苏州 · 姑苏水乡双塔之门",
    features: "东方之门现代拱门天际、苏州园林白墙黛瓦、单孔石拱桥与乌篷船",
    keywords: ["姑苏", "东方之门", "水乡", "拙政园", "石拱桥"],
    colors: "粉墙黛瓦黑 · 浅天青 · 庭园碧绿",
    theme: "Suzhou, Gate to the East and Water Town Stone Bridge",
    silhouette: "the towering modern arch silhouette of the Gate to the East (Oriental Arc) rising in harmony behind classical whitewashed Suzhou canal houses, a single-arch stone bridge, and a traditional black-awning awning boat",
    colorPrompt: "ink wash charcoal black, celadon lake blue, and garden moss green"
  },
  {
    id: 12,
    file: "12_天津.png",
    name: "天津",
    city: "天津",
    region: "华北",
    title: "天津 · 津门海河摩天巨轮",
    features: "天津之眼跨河摩天轮、海河游船波纹、解放桥钢架与望海楼古意",
    keywords: ["津门", "天津之眼", "海河", "解放桥", "古文化街"],
    colors: "海河石青 · 砖红 · 铜绿",
    theme: "Tianjin, Tianjin Eye Ferris Wheel over Haihe River",
    silhouette: "the majestic giant Ferris wheel of the Tianjin Eye built directly across the Yongle Bridge over the tranquil Haihe River, framed by historic European concession architecture and classic arched bridge lines",
    colorPrompt: "Haihe river slate blue, warm brick red, and antique patina green"
  },
  {
    id: 13,
    file: "13_长沙.png",
    name: "长沙",
    city: "长沙",
    region: "华中",
    title: "长沙 · 星城橘洲爱晚枫亭",
    features: "橘子洲头青年毛泽东石雕远眺大江、岳麓山爱晚亭重檐攒尖、杜甫江阁",
    keywords: ["星城", "橘子洲", "爱晚亭", "岳麓山", "湘江"],
    colors: "枫叶浅红 · 湘江蓝 · 黛墨",
    theme: "Changsha, Orange Isle and Aiwan Pavilion of Mount Yuelu",
    silhouette: "the monumental head sculpture silhouette at the tip of Orange Isle in the middle of the flowing Xiang River, harmonized with the upturned eaves of the historic Aiwan Pavilion nestled among stylized autumn maple trees",
    colorPrompt: "autumn maple crimson, Xiang River water blue, and deep charcoal black"
  },
  {
    id: 14,
    file: "14_郑州.png",
    name: "郑州",
    city: "郑州",
    region: "华中",
    title: "郑州 · 中原商都二七红塔",
    features: "二七纪念塔五角双塔并联、黄河大桥远景、古商代城墙夯土遗风",
    keywords: ["商都", "二七塔", "黄河", "中原", "枢纽"],
    colors: "塔砖朱红 · 琉璃绿 · 墨灰",
    theme: "Zhengzhou, Erqi Memorial Tower and Yellow River Monument",
    silhouette: "the distinctive conjoined twin pentagonal towers of the Erqi Memorial Tower with multi-tiered green glazed eaves, anchored beside bold rhythmic lines of an ancient Shang dynasty earthen city rampart and Yellow River waves",
    colorPrompt: "monument crimson red, glazed tile jade green, and graphite grey"
  },
  {
    id: 15,
    file: "15_青岛.png",
    name: "青岛",
    city: "青岛",
    region: "华东",
    title: "青岛 · 琴岛回澜红瓦绿树",
    features: "栈桥回澜阁八角琉璃飞檐、红瓦绿树碧海蓝天、小青岛白色灯塔与海浪",
    keywords: ["琴岛", "栈桥", "回澜阁", "红瓦绿树", "小青岛"],
    colors: "碧海深蓝 · 红瓦赤 · 浪花米白",
    theme: "Qingdao, Zhanqiao Pier Huilan Pavilion and Coastline",
    silhouette: "the long curved stone Zhanqiao Pier extending into the azure sea, leading to the octagonal two-story Huilan Pavilion with sweeping eaves, framed by pine trees on seaside red granite rocks and white sea waves",
    colorPrompt: "ocean indigo blue, terracotta roof tile red, and warm mineral white"
  },
  {
    id: 16,
    file: "16_宁波.png",
    name: "宁波",
    city: "宁波",
    region: "华东",
    title: "宁波 · 甬城书香天一三江",
    features: "天一阁明代古藏书楼重檐、三江口水波交汇、宁波大剧院贝壳天际",
    keywords: ["甬城", "天一阁", "三江口", "书香", "东海"],
    colors: "藏书木褐 · 东海苍青 · 瓦墨",
    theme: "Ningbo, Tianyi Pavilion Library and Sanjiangkou Confluence",
    silhouette: "the serene wooden timber structure of Tianyi Pavilion—China's oldest private library—with lotus pond reflections and stone courtyard rocks, integrated with the flowing waves of the three merging rivers at Sanjiangkou",
    colorPrompt: "antique book timber brown, East China Sea deep teal, and roof tile black"
  },
  {
    id: 17,
    file: "17_厦门.png",
    name: "厦门",
    city: "厦门",
    region: "华东",
    title: "厦门 · 鹭岛琴音日光琴屿",
    features: "鼓浪屿日光岩巨石红亭、郑成功巨型石雕、世茂海峡双子塔帆船天际",
    keywords: ["鹭岛", "鼓浪屿", "日光岩", "双子塔", "琴岛"],
    colors: "鹭岛蔚蓝 · 赤岩赭 · 茉莉白",
    theme: "Xiamen, Gulangyu Sunlight Rock and Shimao Twin Towers",
    silhouette: "the craggy crown of Sunlight Rock overlooking the red-roofed villas of Gulangyu Island, juxtaposed against the soaring curved sail-shaped Shimao Twin Towers skyline across the sparkling sea channel with soaring egrets",
    colorPrompt: "coastal turquoise blue, Sunlight Rock ochre brown, and mineral white"
  },
  {
    id: 18,
    file: "18_昆明.png",
    name: "昆明",
    city: "昆明",
    region: "西南",
    title: "昆明 · 春城滇池金马碧鸡",
    features: "金马碧鸡坊雕梁画栋精美木牌楼、滇池万顷碧波、红嘴鸥飞掠、西山睡美人",
    keywords: ["春城", "金马碧鸡坊", "滇池", "红嘴鸥", "西山"],
    colors: "孔雀翠绿 · 金马明黄 · 滇池蓝",
    theme: "Kunming, Golden Horse and Jade Rooster Archways by Dianchi Lake",
    silhouette: "the elaborate carved wooden archway of the Golden Horse and Jade Rooster Archways with upturned layered eaves, set against the mountain silhouette of Western Hill above Dianchi Lake with flying red-billed seagulls",
    colorPrompt: "peacock jade green, radiant ochre gold, and mountain lake blue"
  },
  {
    id: 19,
    file: "19_大连.png",
    name: "大连",
    city: "大连",
    region: "东北",
    title: "大连 · 滨城星海电车踏浪",
    features: "星海湾跨海大桥海上 S 弯道、老式有轨电车绿皮车厢、海鸥与滨海栈道",
    keywords: ["滨城", "星海大桥", "有轨电车", "星海湾", "海风"],
    colors: "极光深蓝 · 铁轨墨灰 · 浪花白",
    theme: "Dalian, Xinghai Bay Cross-Sea Bridge and Vintage Tramway",
    silhouette: "the graceful curving S-shaped span of the Xinghai Bay Cross-Sea Bridge hovering over ocean swells, paired with the nostalgic silhouette of a classic vintage city tramway car surrounded by seagulls",
    colorPrompt: "deep marine navy blue, steel charcoal grey, and froth white"
  },
  {
    id: 20,
    file: "20_沈阳.png",
    name: "沈阳",
    city: "沈阳",
    region: "东北",
    title: "沈阳 · 盛京故都大政龙阁",
    features: "沈阳故宫大政殿八角重檐攒尖顶、十王亭八字排开、张氏帅府大青楼",
    keywords: ["盛京", "沈阳故宫", "大政殿", "十王亭", "关外"],
    colors: "盛京琉璃金 · 宫墙赤 · 砖雕青灰",
    theme: "Shenyang, Mukden Palace Hall of Great Affairs (Dazheng Hall)",
    silhouette: "the octagonal pyramidal double-eaved Hall of Great Affairs (Dazheng Hall) of the Shenyang Imperial Palace with golden glazed tile roof and carved dragon pillars, framed by historic Manchurian brick pavilion walls",
    colorPrompt: "imperial glazed gold, palace cinnabar red, and antique brick grey"
  },
  {
    id: 21,
    file: "21_济南.png",
    name: "济南",
    city: "济南",
    region: "华东",
    title: "济南 · 泉城齐鲁趵突超然",
    features: "趵突泉三窟喷涌激荡雪浪、泺源堂飞檐、大明湖畔超然楼夜映荷花",
    keywords: ["泉城", "趵突泉", "大明湖", "超然楼", "齐鲁"],
    colors: "灵泉碧青 · 楼阁金黄 · 荷花粉",
    theme: "Jinan, Baotu Spring and Chaoran Tower of Daming Lake",
    silhouette: "the legendary three bubbling gushing columns of Baotu Spring tumbling into a clear stone basin framed by the Luoyuan Hall pavilion, paired with the majestic illuminated multistory Chaoran Tower beside blooming lotus leaves",
    colorPrompt: "pure spring turquoise green, architectural warm ochre, and soft lotus pink"
  },
  {
    id: 22,
    file: "22_合肥.png",
    name: "合肥",
    city: "合肥",
    region: "华东",
    title: "合肥 · 庐州包公清风水阁",
    features: "包公园清风阁五层重檐仿宋水阁、浮庄粉墙黛瓦、八百里巢湖烟波",
    keywords: ["庐州", "清风阁", "包公园", "巢湖", "科创"],
    colors: "湖水碧青 · 阁檐暗褐 · 远山墨",
    theme: "Hefei, Qingfeng Pavilion in Lord Bao Park and Chaohu Lake",
    silhouette: "the towering five-tiered Song-style Qingfeng Pavilion standing proudly on the lakeshore of Lord Bao Park, its intricate multi-layered wooden brackets and eaves reflected in tranquil water ripples with weeping willows",
    colorPrompt: "lake emerald green, weathered timber brown, and soft ink black"
  },
  {
    id: 23,
    file: "23_福州.png",
    name: "福州",
    city: "福州",
    region: "华东",
    title: "福州 · 榕城坊巷马鞍风流",
    features: "三坊七巷流线型马鞍墙屋脊、镇海楼屏山远眺、乌塔与白塔双塔遥望",
    keywords: ["榕城", "三坊七巷", "马鞍墙", "镇海楼", "双塔"],
    colors: "飞檐黛黑 · 砖墙米白 · 苍榕深绿",
    theme: "Fuzhou, Sanfang Qixiang Saddle Roof Walls and Ancient Banyan Trees",
    silhouette: "the sweeping lyrical silhouette of white-walled plaster saddle-shaped firewalls (Maan walls) of Three Lanes and Seven Alleys, crowned by an immense ancient twisted banyan tree canopy and the Zhenhai Tower watchtower on Pingshan",
    colorPrompt: "calligraphy carbon black, warm limestone white, and banyan foliage green"
  },
  {
    id: 24,
    file: "24_哈尔滨.png",
    name: "哈尔滨",
    city: "哈尔滨",
    region: "东北",
    title: "哈尔滨 · 冰城索菲亚穹顶金光",
    features: "圣索菲亚大教堂拜占庭绿色洋葱穹顶、红砖十字墙体、松花江滨铁桥",
    keywords: ["冰城", "索菲亚大教堂", "中央大街", "松花江", "冰雪"],
    colors: "苍绿穹顶 · 红砖赤 · 霜雪冷蓝",
    theme: "Harbin, Saint Sophia Cathedral and Songhua River Railway Bridge",
    silhouette: "the monumental Byzantine Russian-style central green onion dome and soaring tent belfry of Saint Sophia Cathedral, adorned with rich red brick patterns and paired with the steel lattice spans of the Songhua River railway bridge",
    colorPrompt: "oxidized copper green, weathered red brick, and frosted winter blue"
  },
  {
    id: 25,
    file: "25_长春.png",
    name: "长春",
    city: "长春",
    region: "东北",
    title: "长春 · 北国春城同德雕楼",
    features: "伪满皇宫同德殿二层琉璃攒尖顶、新民大街历史街区、红旗街绿皮有轨电车",
    keywords: ["春城", "同德殿", "伪满皇宫", "有轨电车", "净月潭"],
    colors: "宫廷明黄 · 墨绿车身 · 冰石灰",
    theme: "Changchun, Tongde Hall of Museum of the Imperial Palace of Manchukuo",
    silhouette: "the striking hybrid Eastern and Western architectural roof of Tongde Hall with glazed yellow hip-and-gable eaves, accompanied by an iconic historic green electric trolley car running beneath rows of tall poplar trees",
    colorPrompt: "imperial mustard yellow, forest tramway green, and granite stone grey"
  },
  {
    id: 26,
    file: "26_南昌.png",
    name: "南昌",
    city: "南昌",
    region: "华中",
    title: "南昌 · 豫章飞阁滕王临江",
    features: "滕王阁重檐九重天大阁雄姿、赣江之畔落霞孤鹜、秋水共长天一色",
    keywords: ["豫章", "滕王阁", "赣江", "秋水长天", "落霞孤鹜"],
    colors: "飞阁流丹红 · 碧瓦绿 · 晚霞江蓝",
    theme: "Nanchang, Pavilion of Prince Teng overlooking Gan River",
    silhouette: "the magnificent multi-story Pavilion of Prince Teng with flying scarlet brackets and jade-green glazed eaves rising above stone terraces on the banks of the wide Gan River, with a lone wild duck flying toward sunset clouds",
    colorPrompt: "vermilion pavilion red, jade green glaze, and Gan river twilight blue"
  },
  {
    id: 27,
    file: "27_贵阳.png",
    name: "贵阳",
    city: "贵阳",
    region: "西南",
    title: "贵阳 · 林城胜境甲秀浮玉",
    features: "南明河巨石鳌矶上的甲秀楼三层三檐八角尖顶、浮玉桥九孔涵洞、涵碧亭",
    keywords: ["林城", "甲秀楼", "浮玉桥", "南明河", "筑城"],
    colors: "鳌矶石青 · 雕梁暖褐 · 碧水苍绿",
    theme: "Guiyang, Jiaxiu Tower on Nanming River Ao Rock",
    silhouette: "the three-story triple-eaved octagonal Jiaxiu Tower perched gracefully upon the ancient turtle-shaped Ao Rock in the Nanming River, connected by the multi-arched Fuyu Bridge with flowing river currents and riverside weeping willows",
    colorPrompt: "river stone dark teal, aged cedar timber brown, and stream willow green"
  },
  {
    id: 28,
    file: "28_南宁.png",
    name: "南宁",
    city: "南宁",
    region: "华南",
    title: "南宁 · 绿城朱槿国际新姿",
    features: "南宁国际会展中心十二花瓣朱槿花穹顶、青秀山龙象塔眺望、邕江蜿蜒",
    keywords: ["绿城", "会展中心", "朱槿花", "青秀山", "邕江"],
    colors: "朱槿艳红 · 邕江翠绿 · 晴空蓝",
    theme: "Nanning, International Convention Center Hibiscus Dome and Mount Qingxiu",
    silhouette: "the dramatic blooming twelve-petaled hibiscus flower dome of the Nanning International Convention Center rising against lush tropical hills, harmonized with the ancient Longxiang Pagoda of Qingxiu Mountain above the Yong River",
    colorPrompt: "hibiscus petal crimson, subtropical foliage emerald, and clear sky blue"
  },
  {
    id: 29,
    file: "29_海口.png",
    name: "海口",
    city: "海口",
    region: "华南",
    title: "海口 · 椰城骑楼云洞海韵",
    features: "海口骑楼老街南洋巴洛克山花雕栏、海口湾云洞图书馆曲面孔洞、椰树斜影",
    keywords: ["椰城", "骑楼老街", "云洞图书馆", "海口湾", "椰林"],
    colors: "骑楼米褐 · 椰林翠绿 · 琼海天蓝",
    theme: "Haikou, Qilou Old Street and Wormhole Library on Haikou Bay",
    silhouette: "the ornate Baroque colonial pediments and arched arcades of Haikou Qilou arcade street, blending seamlessly with the futuristic organic curving oval window voids of the Wormhole Library and leaning coastal coconut palms",
    colorPrompt: "limestone arcade cream, tropical palm green, and South China Sea sky blue"
  },
  {
    id: 30,
    file: "30_兰州.png",
    name: "兰州",
    city: "兰州",
    region: "西北",
    title: "兰州 · 金城黄河铁桥飞虹",
    features: "黄河第一桥中山铁桥五孔拱形钢桁架、白塔山白塔古刹、滚滚黄河水车",
    keywords: ["金城", "中山铁桥", "黄河第一桥", "白塔山", "大水车"],
    colors: "铁桥钢灰 · 滚滚黄河赭 · 白塔铅白",
    theme: "Lanzhou, Zhongshan Bridge (First Bridge of Yellow River) and Baita Mountain",
    silhouette: "the monumental steel arch trusses of Zhongshan Iron Bridge spanning across the churning Yellow River, with the white multi-tiered Buddhist stupa of Baita Mountain perched high on the barren loess mountain ridge behind",
    colorPrompt: "bridge steel charcoal grey, Yellow River turbulent ochre, and stupa chalk white"
  }
];

function buildPrompt(item) {
  return `A clean minimalist hand-carved rubber stamp artwork centered on 4:5 vertical warm textured aged Xuan paper. The stamp artwork occupies about 65-70% of the canvas height, surrounded by a balanced 30% clean empty negative space with elegant margins. Theme: ${item.theme}. Extremely simplified iconic silhouette of ${item.silhouette}. Minimalist bold carved linocut relief lines, uncluttered composition, 2-3 muted spot colors: ${item.colorPrompt}. Rough dry rubber stamp texture with subtle carved imperfections on fibrous paper. Pure isolated stamp artwork with clean negative space around it, NO full-bleed background, NO full scenery clutter, absolutely NO text, NO letters, NO words, NO characters, NO typography, no watermark.`;
}

module.exports = { ITEMS, buildPrompt };
